### ISSUE TITLE
Milestone 2 > Backend > Define Models

### ISSUE THREAD

**Issue by TravisIngram** [TravisIngram/Dead-List#10]
## Milestone 2 - Backend - Define Models

There are a number of different models that will need to be defined for the various aspects of the app.  These will include a `User`, a `Call`, a `Pun`, the `Deceased`, and likely others.

### User Model
 - [x] The user model defines registered members of the site and the information required for them to use it.
  * Username
  * First Name
  * Last Name
  * Email Address
  * Password
  * Authorization
  * ... 
 
### Call Model
 - [x] The call model defines the primary purpose of the site, announcing the death of a famous person.
 * Title
 * Link (to verifying source...)
 * Comment
 * Timestamp
 * Rating
 * Caller (fk)
 * Pun (fk)
 * ...
 
### Pun Model
 - [x] The pun model defines the contents of the pun as well as the associated information.
 * Content
 * Timestamp
 * Rating
 * User (fk)
 * Call (fk)
* ...

### Deceased Model
 - [x] The deceased model defines the decedent and relevant information about them.
 * Name
 * Date of Death
 * Biography
 * Link
 * ...

----

### Deliverables

* Create models for each of the items above.
`../Dead-List/backend/deadlist/models.py`

**Comment by TravisIngram** [comment]
The initial models have been defined and implemented. More work will likely be needed or modification done. I've already run into issues with whether various fields should be blank so have to think through that a bit more.
