### ISSUE TITLE
Milestone 1 > Project Summary > Installation / Getting Started

### ISSUE THREAD

**Issue by TravisIngram** [TravisIngram/Dead-List#2]
### Milestone 1 - Project Summary - Installation / Getting Started

The project summary is meant to clearly define the various goals and objectives of the project. This summary will include a description of the app; what it is and why it's important, as well as how to install and use it. Some form of license should be included as well.

----

The intent of this task is to create the __*Installation*__ and __*Getting Started*__ documentation for the project.

#### Deliverables

- [x] Add the basic _Installation_ and _Getting Started_ documentation to the `README.md`
- [x] The specific instructions will depend on the technical implementation of the app, but should include everything a new user would need to get it installed and running
- [x] The getting started documentation ought to include basic instructions on how to actually use the application.
  * Potential to include some initial data to populate the app 
- [x] Add license wording to the README document

**Comment by TravisIngram** [comment]
Updated the main README with initial installation and getting started instructions.

May need to add some additional instructions on actual use of the application.
