### ISSUE TITLE
Milestone 1 > User Stories > Define Stories

### ISSUE THREAD

**Issue by TravisIngram** [TravisIngram/Dead-List#3]
### Milestone 1 - User Stories - Define Stories

**User Stories** are used to help understand how the application could be or will be used.  They often form the basis of feature development and ensure that basic functionality is present.  Each story created should also include **Acceptance Criteria** which lay out what needs to be done to achieve or finish a given story.

Just as user stories drive development and help ensure our application fills its core purpose, **Mis-user Stories** are used to make sure the application is properly protected against potential threats and malicious actors.  Each of these stories should include corresponding **Mitigation Criteria** to help define how a particular threat is remediated.

----

The intent of this task is to create a set of basic __*User Stories*__ for the application. They should follow the structure outlined below.
```
As a **user/role**, I want to **goal** so I can **rationale**.
```
#### Deliverables

- [x] Create a `docs` directory in the base repository of the project
- [x] **User Stories** should be added to a `README.md` file within the `docs` directory
- [x] Create unique stories for the basic functionality of the application, from unauthenticated, authenticated, and admin user perspective
  * Browsing / posting / commenting / managing user and posts
- [x] Create _Acceptance Criteria_ for each user story

**Comment by TravisIngram** [comment]
Here are the initial user stories for this site.

----

**Unauthenticated User**

* As an _unauthenticated_ user I want to browse recent celebrity deaths and select individuals to read more about them and what folks had to say.

**Authenticated User**

* As an _authenticated_ user I want to be able to post ('call') a new celebrity death.

* As an _authenticated_ user I want to be able to edit my posts.

* As an _authenticated_ user I want to be able to respond to other users posts.

* As an _authenticated_ user I want to be able to rate other users comments (puns).

**Admin User**

* As an _administrator_ (admin user) I want to be able to manage users of the site. (add / remove)

* As an _administrator_ (admin user) I want to be able to manage posts made to the site. (add / remove)

**Comment by TravisIngram** [comment]
I updated the user stories and their respective acceptance criteria.

1. As a _visitor_ to the Dead List I want to _browse_ recent celebrity deaths in order to _learn about them_ and read the puns that members of the site made about them.
 * Acceptance Criteria:
   * The site has proper views that display each call that was made as well as the images and biographical information about the deceased.

**Authenticated User**

2. As a _member_ of the Dead List, I want to be able to _post_ (`call`) a new death _in order to be the first person to do so_.
 * Acceptance Criteria:
   * Members can click on the `Make Call` button and enter the necessary information to add a new post.

3. As a _member_ of the Dead List, I want to be able to _edit_ any posts (`puns`) I make _in order to clarify intent or correct mistakes_.
 * Acceptance Criteria:
   * Members can select and edit their own calls or puns for clarity or to add more information.

4. As a _member_ of the Dead List, I want to be able to _respond_ to other users posts (`calls`), _in order to share puns_.
 * Acceptance Criteria:
   * Members are able to add or make puns related to a given call.

5. As a _member_ of the Dead List, I want to be able to _rate_ other users comments (`puns`) _in order to show my appreciation or aversion_ for their humor.
 * Acceptance Criteria:
   * Members are able to up or down vote puns other users make on a given call.
   * Ratings are displayed next to each pun

**Admin User**

6. As the _administrator_ of the Dead List, I want to be able to _manage_ users of the site (remove) _in order to maintain a positive environment_.
 * Acceptance Criteria:
   * The administrator is able to remove / delete a user from the site.

7. As the _administrator_ of the Dead List, I want to be able to _manage_ (edit) posts (calls / puns) made to the site _in order to ensure negative or offensive content isn't shared_.
 * Acceptance Criteria:
   * The administrator is able to remove any call or pun made.
   * The administrator is able to update the content of any call or pun made.
