### ISSUE TITLE
Milestone 1 > User Stories > Define Mis-user Stories

### ISSUE THREAD

**Issue by TravisIngram** [TravisIngram/Dead-List#4]
### Milestone 1 - User Stories - Define Mis-user Stories

**User Stories** are used to help understand how the application could be or will be used.  They often form the basis of feature development and ensure that basic functionality is present.  Each story created should also include **Acceptance Criteria** which lay out what needs to be done to achieve or finish a given story.

Just as user stories drive development and help ensure our application fills its core purpose, **Mis-user Stories** are used to make sure the application is properly protected against potential threats and malicious actors.  Each of these stories should include corresponding **Mitigation Criteria** to help define how a particular threat is remediated.

----

The intent of this task is to create a set of basic __*Mis-user Stories*__ for the application. They should follow the structure outlined below. In addition, **Mitigation Criteria** should be included for each mis-user story identified.
```
As a **user/role**, I want to **goal** so I can **rationale**.
```
#### Deliverables

- [x] **Mis-user Stories** should be added to a `README.md` file within the `docs` directory
- [x] Create mis-user stories for basic / common attacks against the application. These should include common attacks from the [OWASP Top 10](https://owasp.org/www-project-top-ten/)
  * Injection / Broken authentication / XSS and so on...
- [x] Add mitigation criteria for each mis-user story.

**Comment by TravisIngram** [comment]
Added initial mis-user stores.

**Comment by TravisIngram** [comment]
Added the following mis-user stories and some associated mitigation criteria.

----

The **Mis-user Stories** for a mischievous member, disgruntled member, cheating member are listed below.  The **Mitigation Criteria** are listed in-line with each story.

1. As a _mischievous member_ I want to _deface the site_ by _inserting malicious code_ when posting.
 * Mitigation Criteria:
   * Validate input from all fields.
   * Use Object-Relational Mapping instead of raw SQL when communicating with the DB.

2. As a _disgruntled member_ I want to _redirect visitors_ to a malicious site by _adding new HTML/JS_ via text fields.
 * Mitigation Criteria:
   * Ensure input is properly escaped.

3. As a _cheating member_ I want to _add upvotes_ of my posts by _editing my rating count_.
 * Mitigation Criteria:
   * Ensure proper permissions exist so users can only modify specific fields of their own posts.
