### ISSUE TITLE
Milestone 2 > FrontEnd > Views...

### ISSUE THREAD

**Issue by TravisIngram** [TravisIngram/Dead-List#8]
## Milestone 2 - FrontEnd - Define Views

The site will need to have a number of distinct views based on the task or activity that a given user is performing. The following views are based off of the initial mockups. There will likely need to be more added as the site develops.

This is an outline of the individual views.  Each of these will need to have their own issue to track work done on them.

### Landing Page / Home page
- [x] This constitutes the default view for the application and will include a carousel of calls as well as a table view of recent calls.

### Recent Calls
- [x] This view will be comprised of a table view of the **XX** number of recent calls.

### Details
- [x] This view provides additional information about a given call and includes the following;
  * Call details (Who called, when, link, puns)
  * Biographical information
  * Image, if available 

### Make Call
- [x] This view will provide a form for making a call and include;
  * Person
  * Date of Death
  * Link for verification
  * Any puns / comments
 
### Login / Register
- [x] This view will provide basic login functionality.

### My Calls
- [x] This view will display all the calls made by a given user.
  * Users will be able to edit basic information contained in the original call.

----

### Deliverables

* Create issues for each of these views...

**Comment by TravisIngram** [comment]
Issues for each of the primary views for the site have been created.

Issue #12 Index
Issue #13 All Calls
Issue #14 My calls
Issue #15 Call Detail
Issue #16 Submit Call
Issue #17 Log-in
