### ISSUE TITLE
Milestone 2 > Task List

### ISSUE THREAD

**Issue by TravisIngram** [TravisIngram/Dead-List#9]
## Task List

The intent of this issue is to generate a basic task list for the main blocks of work that will be needed in order to complete this application.  These largely be rough in nature and in need of refinement, but should serve as a basic starting point.

### Backend
- [x] Set up container files (`Dockerfile`, `docker-compose.yml`) to ensure backend components are in place and functioning.
  * Backend components include Django and PostgreSQL and external APIs like Wikipedia...
- [x] Stub out basic application structure within Django
  * This will initially mimic structure from previous lab work
- [x] Set up initial Model / schema for the database
  *  (username, call, pun, rating, timestamp, link, deceasedDoD, deceasedImage, deceasedBio...)
- [x] Set up routes for various views
  * (/, /register, /makeCall, /myCalls, /calls...)
- [x] Set up controllers for the various `URL`s
- [ ] Set up basic testing framework

### Frontend
- [x] Set up / install frontend libraries like Ember, Tabulator...
- [x] Stub out basic application structure
  * Components, routes, models, styles...
- [ ] Set up basic testing framework

### Miscellaneous

**Comment by TravisIngram** [comment]
Added initial Docker files to the project.  I used the base provided by Dr. Hale but will likely have to update them for the final project.  I also stubbed out the initial project structure using Django for the backend and Ember for the front end.

**Comment by TravisIngram** [comment]
Most of the items in this task were broken out and created individually.
